# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\"\x1e\n\x10PostExistRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1f\n\x0ePostExistReply\x12\r\n\x05\x65xist\x18\x01 \x01(\x08\x32\x37\n\x04Post\x12/\n\tPostExist\x12\x11.PostExistRequest\x1a\x0f.PostExistReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTEXISTREQUEST._serialized_start=14
  _POSTEXISTREQUEST._serialized_end=44
  _POSTEXISTREPLY._serialized_start=46
  _POSTEXISTREPLY._serialized_end=77
  _POST._serialized_start=79
  _POST._serialized_end=134
# @@protoc_insertion_point(module_scope)
