# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_server.grpc_output.post_pb2 as post__pb2


class PostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostExist = channel.unary_unary(
                '/Post/PostExist',
                request_serializer=post__pb2.PostExistRequest.SerializeToString,
                response_deserializer=post__pb2.PostExistReply.FromString,
                )


class PostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostExist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostExist': grpc.unary_unary_rpc_method_handler(
                    servicer.PostExist,
                    request_deserializer=post__pb2.PostExistRequest.FromString,
                    response_serializer=post__pb2.PostExistReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Post', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Post(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostExist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Post/PostExist',
            post__pb2.PostExistRequest.SerializeToString,
            post__pb2.PostExistReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
